#!/bin/sh

TOOLS=`dirname $0`
LOKI=`dirname "$TOOLS"`
SUPPORT="$TOOLS/support/"
HELPERS="`dirname $TOOLS`/helpers/python/"

if [ ! -d $HELPERS ]
then
	echo "Python helper code directory could not be located." 1>&2
	exit 1
fi

PYTHONPATH="$HELPERS:$PYTHONPATH" LOKI="$LOKI" python "${SUPPORT}build.py" "$@"